apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-http
  name: node2-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-http
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-http
    spec:
      containers:
      - image: kgopi1/fluxlab:latest
        name: node-http
        resources: {}
status: {}
